### ISSUE TITLE
Can this work for 'the artifact of the current project'?

### ISSUE THREAD

**Issue by benson-basis** [veithen/alta#1]
For very small projects, it's useful to have a quick OSGi integration test _right here_. It's a shame to have to make a single-module project into a two-module project just for one test. Could this plugin make a link file that just points to the bundle as built in 'target'?

**Comment by veithen** [comment]
Some random thoughts about this.

These types of tests only work with fully packaged artifacts. If you want to execute them in the same module, you need to execute them as integration tests (a la failsafe) rather than unit tests (a la surefire). That shouldn't be a problem. On the other hand, it also means that the `alta:generate-test-resources` goal isn't appropriate for that use case:

* By default it is executed in the `generate-test-resources` phase.
* If you configure it to run after the package phase, it will still add an entry to the project's test resources, but that won't have any effect.

One possible way to support your use case would be to use the alta:generate-files goal instead (and use something like `link:file:target/links/mybundle.link` as URL) and to add a feature to the plugin that mimics the `useProjectArtifact` property supported by `maven-assembly-plugin`).

WDYT?
