### ISSUE TITLE
compile scope includes provided artifacts. Could it not?

### ISSUE THREAD

**Issue by benson-basis** [veithen/alta#4]
I end up trying to provision

```
<dependency>
            <groupId>org.osgi</groupId>
            <artifactId>osgi.cmpn</artifactId>
            <version>6.0.0</version>
            <scope>provided</scope>
        </dependency>
```

which does not work.

**Comment by veithen** [comment]
The scope filtering is done using standard Maven code:

https://github.com/apache/maven/blob/maven-3.3.9/maven-core/src/main/java/org/apache/maven/artifact/resolver/filter/AbstractScopeArtifactFilter.java

I don't like the idea to change that behavior because it would make it inconsistent with other Maven plugins. Wouldn't "runtime" (which doesn't include "provided") instead of "compile" be more appropriate for your use case?

**Comment by benson-basis** [comment]
Fair enough.
